const jobs = [
  {
    id: 1,
    company: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    posted: "2 weeks ago",
    title: "Backend Developer",
    type: "Full Time",
    level: "Mid Level",
    salary: "$70/hour",
    location: "Mumbai, India",
  },
  {
    id: 2,
    company: "Microsoft",
    logo: "https://logo.clearbit.com/microsoft.com",
    posted: "4 weeks ago",
    title: "Data Scientist",
    type: "Full Time",
    level: "Junior Level",
    salary: "$90/hour",
    location: "Hyderabad, India",
  },
  {
    id: 3,
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    posted: "1 week ago",
    title: "Frontend Developer",
    type: "Remote",
    level: "Senior Level",
    salary: "$85/hour",
    location: "Bengaluru, India",
  },
  {
    id: 4,
    company: "IBM",
    logo: "https://logo.clearbit.com/ibm.com",
    posted: "3 days ago",
    title: "AI Research Engineer",
    type: "Full Time",
    level: "Mid Level",
    salary: "$95/hour",
    location: "Pune, India",
  },
  {
    id: 5,
    company: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    posted: "5 days ago",
    title: "UI/UX Designer",
    type: "Contract",
    level: "Senior Level",
    salary: "$65/hour",
    location: "Noida, India",
  },
  {
    id: 6,
    company: "Netflix",
    logo: "https://logo.clearbit.com/netflix.com",
    posted: "6 days ago",
    title: "DevOps Engineer",
    type: "Full Time",
    level: "Senior Level",
    salary: "$110/hour",
    location: "Remote",
  },
  {
    id: 7,
    company: "Meta",
    logo: "https://logo.clearbit.com/meta.com",
    posted: "1 day ago",
    title: "React Developer",
    type: "Remote",
    level: "Mid Level",
    salary: "$80/hour",
    location: "Gurugram, India",
  },
  {
    id: 8,
    company: "Apple",
    logo: "https://logo.clearbit.com/apple.com",
    posted: "2 days ago",
    title: "iOS Developer",
    type: "Full Time",
    level: "Senior Level",
    salary: "$120/hour",
    location: "Bengaluru, India",
  },
];

export default jobs;